version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./app/
      dockerfile: Dockerfile
    container_name: example-app-symfony
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./app/:/var/www
    environment:
      CACHE_DRIVER: memcached
      MEMCACHED_HOST: memcached
      MEMCACHED_PORT: 11211
      MESSENGER_TRANSPORT_DSN: redis://localhost:6379/messages
    networks:
      - app-network
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    container_name: example-app-symfony-ngnix
    restart: unless-stopped
    ports:
      - 8081:80
    volumes:
      - ./app/:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
